### ISSUE TITLE
Can't get version 3.0.1 from Jitpack

### ISSUE THREAD

**Issue by Vanamas** [atomfrede/jadenticon#22]
It seems something is wrong with version 3.0.1.

I tried to get this version via gradle. All I have set and Android Studio is showing no message about an error but the library doesn't appear in external libraries list.

When I switch to version 2.0.0 then library will appear in external libraries list.

**Comment by atomfrede** [comment]
Sorry @Vanamas somehow I missed the notification (`TooManyNotificationsException`). 

From the jitpack log it seems like it has been [build correctly](https://jitpack.io/com/github/atomfrede/jadenticon/3.0.1/build.log), but I admit I didn't test it with a real project. Will try it this week and post my results here.

**Comment by atomfrede** [comment]
I tried via maven and indeed it seems not to work. Using gradle it compiled, will try to investigate further.

**Comment by dmeiners88** [comment]
The jitpack build log for [3.0.1](https://jitpack.io/com/github/atomfrede/jadenticon/3.0.1/build.log) does not contain the final jar, only a sources.jar. Somehow the build itself does not create the normal jar anymore?

**Comment by atomfrede** [comment]
❤️ Thanks for taking a second look. I didn't notice. Will try to check whats going on. Building it locally worked if I remember correctly.

**Comment by atomfrede** [comment]
It should be fixed. The build log looks good. You can give it a try.

**Comment by dmeiners88** [comment]
Confirmed. Version 3.0.2 works as expected. Thanks!
