### ISSUE TITLE
Gradle errors

### ISSUE THREAD

**Issue by shrenuj** [atomfrede/jadenticon#7]
Adding dependencies in Android studio Gradle leads to this warning

Warning:Dependency commons-logging:commons-logging:1.0.4 is ignored for debug as it may be conflicting with the internal version provided by Android.

Also,it results in an error
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK license/LICENSE.dom-documentation.txt
	File1: C:\Users\user\.gradle\caches\modules-2\files-2.1\xml-apis\xml-apis\2.0.2\3136ca936f64c9d68529f048c2618bd356bf85c9\xml-apis-2.0.2.jar
	File2: C:\Users\user\.gradle\caches\modules-2\files-2.1\xml-apis\xml-apis-ext\1.3.04\41a8b86b358e87f3f13cf46069721719105aff66\xml-apis-ext-1.3.04.jar

**Comment by atomfrede** [comment]
Hi @shrenuj ,

you can configure your build and [exclude the copied twice files.](http://stackoverflow.com/questions/32901401/gradle-build-error-errorexecution-failed-for-task-apptransformresourceswith).

But ``jadenticon`` uses the [nashorn javascript engine](http://www.oracle.com/technetwork/articles/java/jf14-nashorn-2126515.html) internally to wrap the [original javascript library](https://jdenticon.com/). As far as I know android doesn't ship with packages under ``javax`` and still doesn't support java 8. Therefor ``nashorn`` is not available on android and ``jadenticon`` won't work even when you manage to configure your build correctly.
